name: testcafe-webpack-react

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version-file: "testcafe-webpack-react/.nvmrc"
      - name: info
        run: |
          node --version
          npm --version
      - name: install
        run: |
          cd testcafe-webpack-react
          npm install
      - name: run
        run: |
          cd testcafe-webpack-react
          npm test
